version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mongodb
      - DB_DATABASE_URL=mongodb+srv://tziprincii434_db_user:46bFRGvaU0D2qeMl@ompay.shuqnnd.mongodb.net/?appName=ompay
    networks:
      - ompay-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "9092:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb+srv://tziprincii434_db_user:46bFRGvaU0D2qeMl@ompay.shuqnnd.mongodb.net/?appName=ompay
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - ompay-network

volumes:
  mongodb_data:

networks:
  ompay-network:
    driver: bridge